### ISSUE TITLE
Server crash with card config 

### ISSUE THREAD

**Issue by Saereth** [Swedz/MI-Tweaks#2]
The lastest version of MI Tweaks and MI on NeoForge 1.20.4 causes a server crash when attempting to apply camouflage to blocks. Here is a crashlog

https://pste.ch/siwukijeqi.coffeescript

I checked with Technici4n and they said it was on MI Tweaks causing the crash. If you need any additional info let me know, ty!

**Comment by Swedz** [comment]
This is a silly mistake on my part, pretty similar to the other issue from last night. Out of curiosity, does this happen only when you use the pipe config card?

**Comment by Saereth** [comment]
it seems to yeah, not sure if it could be triggered any other way but this is all we've found to crash so far

**Comment by Swedz** [comment]
Fixed in d17dad0. Will release a 1.0.2+1.20.4 version in a few mins here, may take some time for CF to approve
